# Generated by Django 5.0.4 on 2024-04-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isDelivered',
        ),
    ]
